apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
# default key value pair
type: Opaque
# the actual contents key-value pairs
data:
  # value base64 encoded
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
